# Generated by Django 6.0.4 on 2026-04-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_donation_newslettersubscriber_brainstormidea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_format',
            field=models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown'), ('html', 'HTML')], default='markdown', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
    ]
