# Generated by Django 6.0.4 on 2026-04-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blogpost_body_format_blogpost_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
