# Generated by Django 5.2.4 on 2026-04-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_avatar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ceo', 'CEO'), ('coo', 'COO')], default='coo', max_length=20),
        ),
    ]
