# Generated by Django 5.2.4 on 2026-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teammember_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hero_image_file',
            field=models.FileField(blank=True, null=True, upload_to='content/posts/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='content/gallery/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar_file',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
